---
# Copyright (C) 2015 PSP2SDK Project
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

sudo: required

before_install:
 - set -e

 - sudo add-apt-repository -y ppa:terry.guo/gcc-arm-embedded
 - sudo apt-get update -qq -y
 - sudo apt-get install -qq gcc-arm-none-eabi

 - git clone git://github.com/psp2sdk/libs "$PSP2LIBS"

script:
 - export FILE=psp2-multilib-dirty-$(git describe --always).zip

 - aclocal
 - automake --add-missing
 - autoconf

 - mkdir out
 - cd out
 - ../configure $FLAGS || cat config.log
 - make install -j4

 - mkdir fpu
 - cd fpu
 - ../../configure $FLAGS --with-fpu
 - make install -j4
 - cd ..

 - mkdir thumb
 - cd thumb
 - ../../configure $FLAGS --with-thumb
 - make install -j4

 - cd $PREFIX/arm-none-eabi/lib
 - zip -0rq $FILE psp2

after_success:
 - curl -q -T $FILE -u $FTP ftp://wololo.net/

env:
 global:
  - PREFIX="$PWD/dist"
  - PSP2LIBS="$PWD/libs"
  - FLAGS="-q --host=arm-none-eabi --with-headers=\"$PSP2LIBS/include\" --prefix=$PREFIX"
  - secure: "tGv0IG9YUFyKa7S+S5faw4uaVt8dJC7jycAxtYCYvmZeyqVgQjEOHhErggilzJgnUIUkLM5r3uEzum40qL0EkaJ7ZegKt04A7Fg8ZPzJ5bWYC4X9bHkH68Qjj/Q6lJ+qWqk+Jnk9pDAGQCnYlnDMcmjpo9i2FrZOMvA4FW8WNg0anpihHIP3nao7sCfe2x+cYxTV/xkPW4WK4a3LrkB+rlgUi86nRf2voByaQ3zftZ0irTks557+NPHpiLkfDmOK/sdGyCqI4aii7CVeSzhRoIsMO8CgABrRi6F5obWCqBtVlGNDS4n8sXP513a+gmbMqEquYsoqSPjEWjmjAJYUzn+6Sw0/ShJTAkqPswPiZ65CiijRbHb9BFvm4mqUMK/5/Gp66rVZfbs+E1znhZ7erDGqeWeizmFpzRZFBKpjhtnp2a/yb9SLtORHTGGsIcoRWIfNjQ1TXkcmuCqs7X8o7qEhzARBSby1/dCzjDnPTP8/M9nZGoCuLHTmxepkr52brxFylg1jk0sjo/4aKT0ct4D9anl9yRO4FMdf19NETVixm4LA2cjOkbFLquol/SJv+r4d/PQo/+tQ1TFboT6sMuGgnb00J+9s4U0IwzlnxnXyp8Xn4FBwatwdOx3QR9aFWYiYVyrr/q8EABSTEzi/fjJJKJuejhv8NwjjQzlVlw8="
